Hw6 postgres
SK1995/tfs-admin pull request #3
Opened 2018-07-26 20:40 UTC by SK1995

Домашнее задание по postgresql: запуск postgres и взаимодействие с ним через драйвер psycopg2.
Формулировка задания расположена [тут](https://gitlab.com/tfs_s18_admin/homework/tree/master/materials/class06).

2018-07-28 18:43 UTC, Frodox requested changes

2018-07-28 18:43 UTC, Frodox commented on hw6_postgres/main.py
> +    db_exec(cursor, """ INSERT INTO order_items(order_id, good_id, quantity) VALUES (%s, %s, 42)"""
тут прям SQL-инъекция, не так ли?)
Как правильно пользоваться `psycopg2 execute` ? Давай глянем в доку и переделаем на безопасный вариант http://initd.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries

2018-07-28 18:43 UTC, Frodox commented on hw6_postgres/main.py
> +    print "unable to connect to the database"
ошибки в stderr

2018-07-28 18:43 UTC, Frodox commented on hw6_postgres/README.md
> +Результаты работы можно проверить на виртуальной машине  ```s-27.fintech-admin.m1.tinkoff.cloud``` (все упомянутые в работе файлы лежат в каталоге ```/root/hw6_postgres```).
а-та-та. не нужно без необходимости под `root` работать. Особенно код разрабатывать и исполнять. `sudo` покрывает все случае, а  в этой задаче и права суперпользоателя не нужны)

2018-07-28 18:44 UTC, Frodox commented
А readme хорошее, всё понятно и достаточно полно описано. Код функций только нет необходимости копи-пастить (т.к. это слишком быстро устареет). можно просто сослаться на имя функции

2018-07-28 20:27 UTC, SK1995 commented on hw6_postgres/README.md
> +Результаты работы можно проверить на виртуальной машине  ```s-27.fintech-admin.m1.tinkoff.cloud``` (все упомянутые в работе файлы лежат в каталоге ```/root/hw6_postgres```).
Перенёс файлы с домашним заданием в каталог ```/home/user27/hw6_postgres```, дальнейшие ДЗ тоже буду складывать в ```/home/user27/*```.
От рута не буду запускаться:)

2018-07-28 20:27 UTC, SK1995 commented on hw6_postgres/main.py
> +    db_exec(cursor, """ INSERT INTO order_items(order_id, good_id, quantity) VALUES (%s, %s, 42)"""
> Warning Never, never, NEVER use Python string concatenation (+) or string parameters interpolation (%) to pass variables to a SQL query string. Not even at gunpoint.

Ouch... :) спасибо!
Обновил метод ```db_exec``` в соответствии с документацией psycopg2, теперь передаю параметры запроса в качестве второго аргумента функции ```execute```.

https://github.com/SK1995/tfs-admin/pull/3/commits/a0ed28476056488c7685873d92987d096f1c332b#diff-032502d86a252711772f0bcd5d6c3b80R16

2018-07-28 20:27 UTC, SK1995 commented on hw6_postgres/main.py
> +    print "unable to connect to the database"
Перенаправил ошибки в stderr [в новом коммите](https://github.com/SK1995/tfs-admin/pull/3/commits/a0ed28476056488c7685873d92987d096f1c332b#diff-032502d86a252711772f0bcd5d6c3b80R20).

2018-08-03 11:34 UTC, Frodox approved these changes

2018-08-14 18:27 UTC, merged